[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_FIREBASE_API_KEY = "AIzaSyD_Qbg2oefCrjtjeU1NgytHmZLdrmccE3I"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "symptom-tracker-aydh.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "symptom-tracker-aydh"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "symptom-tracker-aydh.appspot.com"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "660325549468"
  REACT_APP_FIREBASE_APP_ID = "1:660325549468:web:09f8c4bf5bee7fc3cb7459"
  REACT_APP_MEASUREMENT_ID = "G-NB85F1M99S"